# -*- coding: utf-8 -*-
"""AI Prescription.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qqpJVbcj7yWwrKTuXvAxHkdKxxFvWimB
"""

!pip install -q transformers torch gradio huggingface_hub accelerate

# AI Medical Prescription Verification System
# Complete single-cell implementation for Google Colab

# ============================================
# INSTALLATION & SETUP
# ============================================
import subprocess
import sys

print("🔧 Installing required packages...")
packages = [
    "transformers",
    "torch",
    "gradio",
    "accelerate",
    "bitsandbytes"
]

for package in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

print("✅ All packages installed successfully!")

# ============================================
# IMPORTS
# ============================================
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import gradio as gr
import re
from datetime import datetime

# ============================================
# MODEL INITIALIZATION
# ============================================
print("🤖 Loading IBM Granite 3.3 2B Instruct model...")

MODEL_NAME = "ibm-granite/granite-3.1-2b-instruct"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map="auto",
    low_cpu_mem_usage=True
)

print("✅ Model loaded successfully!")

# ============================================
# DRUG DATABASE (Sample - Expand as needed)
# ============================================
DRUG_INTERACTIONS = {
    "aspirin": ["warfarin", "ibuprofen", "clopidogrel"],
    "warfarin": ["aspirin", "ibuprofen", "vitamin k"],
    "metformin": ["alcohol", "contrast dye"],
    "lisinopril": ["potassium", "nsaids"],
    "simvastatin": ["grapefruit", "gemfibrozil"],
    "ibuprofen": ["aspirin", "warfarin", "lisinopril"],
    "amoxicillin": ["methotrexate", "warfarin"],
    "omeprazole": ["clopidogrel", "warfarin"],
    "levothyroxine": ["calcium", "iron supplements"],
    "amlodipine": ["simvastatin", "grapefruit"]
}

DRUG_ALTERNATIVES = {
    "aspirin": ["clopidogrel", "dipyridamole"],
    "ibuprofen": ["naproxen", "celecoxib", "acetaminophen"],
    "omeprazole": ["lansoprazole", "pantoprazole"],
    "metformin": ["glipizide", "sitagliptin"],
    "lisinopril": ["losartan", "valsartan"],
    "simvastatin": ["atorvastatin", "rosuvastatin"],
    "amoxicillin": ["azithromycin", "cephalexin"],
    "amlodipine": ["nifedipine", "diltiazem"]
}

AGE_DOSAGE_RULES = {
    "children": "Children (0-12 years): Reduced dosage - typically 25-50% of adult dose based on weight",
    "teens": "Teens (13-17 years): Adjust to 50-75% of adult dose or use weight-based calculation",
    "adults": "Adults (18-64 years): Standard dosage as prescribed",
    "elderly": "Elderly (65+ years): Reduced dosage - typically 50-75% of standard adult dose due to decreased metabolism"
}

# ============================================
# CORE AI FUNCTIONS
# ============================================

def generate_ai_response(prompt, max_length=512):
    """Generate response using IBM Granite model"""
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_length,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Extract only the response part (after the prompt)
    response = response[len(prompt):].strip()
    return response

def extract_drugs_nlp(prescription_text):
    """Extract drug names using NLP and pattern matching"""
    prompt = f"""Extract all medication names from the following prescription text.
List only the drug names, one per line, without dosages or instructions.

Prescription: {prescription_text}

Drug names:"""

    ai_response = generate_ai_response(prompt, max_length=256)

    # Parse AI response and common patterns
    drugs = []
    lines = ai_response.split('\n')
    for line in lines:
        line = line.strip().strip('-*•').strip()
        if line and len(line) > 2 and not any(x in line.lower() for x in ['drug', 'medication', 'prescription', ':']):
            drugs.append(line.lower())

    # Also use regex patterns for common drug formats
    pattern = r'\b([a-z]+(?:mycin|cillin|azole|prazole|statin|dipine|sartan|olol|pril))\b'
    regex_drugs = re.findall(pattern, prescription_text.lower())
    drugs.extend(regex_drugs)

    # Remove duplicates and return
    return list(set(drugs))[:10]  # Limit to 10 drugs

def check_drug_interactions(drugs):
    """Check for drug interactions"""
    interactions = []
    drugs_lower = [d.lower() for d in drugs]

    for i, drug1 in enumerate(drugs_lower):
        for drug2 in drugs_lower[i+1:]:
            if drug1 in DRUG_INTERACTIONS:
                if any(drug2 in interaction.lower() for interaction in DRUG_INTERACTIONS[drug1]):
                    interactions.append((drug1, drug2))
            if drug2 in DRUG_INTERACTIONS:
                if any(drug1 in interaction.lower() for interaction in DRUG_INTERACTIONS[drug2]):
                    interactions.append((drug2, drug1))

    return list(set(interactions))

def get_age_based_dosage(drug, age, weight=None):
    """Provide age-specific dosage recommendations"""
    age = int(age)

    if age <= 12:
        category = "children"
    elif age <= 17:
        category = "teens"
    elif age <= 64:
        category = "adults"
    else:
        category = "elderly"

    base_info = AGE_DOSAGE_RULES[category]

    # Get AI-enhanced recommendation
    prompt = f"""Provide specific dosage recommendation for {drug} for a {age}-year-old patient.
Consider age-related metabolism and safety. Be specific and medical.

Recommendation:"""

    ai_recommendation = generate_ai_response(prompt, max_length=200)

    return f"{base_info}\n\n🤖 AI Recommendation:\n{ai_recommendation}"

def find_alternatives(drug):
    """Find alternative medications"""
    alternatives = []
    drug_lower = drug.lower()

    # Check database
    if drug_lower in DRUG_ALTERNATIVES:
        alternatives = DRUG_ALTERNATIVES[drug_lower]

    # Get AI suggestions
    prompt = f"""List 3-5 alternative medications for {drug}.
Provide only the drug names and brief reason for each alternative.

Alternatives:"""

    ai_alternatives = generate_ai_response(prompt, max_length=256)

    return {
        "database_alternatives": alternatives,
        "ai_suggestions": ai_alternatives
    }

# ============================================
# GRADIO INTERFACE FUNCTIONS
# ============================================

def verify_prescription(prescription_text, patient_age, patient_weight):
    """Main verification function"""
    if not prescription_text.strip():
        return "⚠️ Please enter a prescription to verify.", "", "", ""

    # Extract drugs
    drugs = extract_drugs_nlp(prescription_text)
    if not drugs:
        return "⚠️ No drugs detected in the prescription. Please check the input.", "", "", ""

    drugs_found = f"### 💊 Detected Medications:\n" + "\n".join([f"- {drug.title()}" for drug in drugs])

    # Check interactions
    interactions = check_drug_interactions(drugs)
    if interactions:
        interaction_text = "### ⚠️ DRUG INTERACTIONS DETECTED:\n\n"
        for drug1, drug2 in interactions:
            interaction_text += f"🔴 **{drug1.title()}** ↔️ **{drug2.title()}**\n"
            interaction_text += f"   - These medications may interact. Consult physician.\n\n"
    else:
        interaction_text = "### ✅ No Known Drug Interactions Detected\n\nAll medications appear safe to take together."

    # Age-based dosage
    dosage_info = ""
    if patient_age:
        dosage_info = "### 📊 Age-Specific Dosage Recommendations:\n\n"
        for drug in drugs[:3]:  # Limit to first 3 drugs for performance
            dosage_info += f"**{drug.title()}:**\n"
            dosage_info += get_age_based_dosage(drug, patient_age, patient_weight) + "\n\n"

    # Alternatives
    alternatives_info = "### 🔄 Alternative Medications:\n\n"
    for drug in drugs[:3]:  # Limit to first 3 drugs
        alts = find_alternatives(drug)
        alternatives_info += f"**For {drug.title()}:**\n"
        if alts["database_alternatives"]:
            alternatives_info += "Database matches: " + ", ".join([a.title() for a in alts["database_alternatives"]]) + "\n"
        alternatives_info += f"{alts['ai_suggestions']}\n\n"

    return drugs_found, interaction_text, dosage_info, alternatives_info

# ============================================
# GRADIO UI
# ============================================

# Custom CSS for attractive design
custom_css = """
.gradio-container {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}
.header {
    text-align: center;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    padding: 30px;
    border-radius: 10px;
    color: white;
    margin-bottom: 20px;
}
.output-box {
    border-left: 4px solid #667eea;
    padding: 15px;
    background: #f8f9fa;
    border-radius: 5px;
    margin: 10px 0;
}
"""

with gr.Blocks(css=custom_css, theme=gr.themes.Soft()) as app:
    gr.HTML("""
        <div class="header">
            <h1>🏥 AI Medical Prescription Verification System</h1>
            <p>Powered by IBM Granite 3.3 2B Instruct | Advanced Drug Safety Analysis</p>
        </div>
    """)

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("## 📝 Input Prescription Details")

            prescription_input = gr.Textbox(
                label="Prescription Text",
                placeholder="Enter prescription here...\nExample: Patient prescribed Aspirin 100mg daily, Lisinopril 10mg daily, and Metformin 500mg twice daily.",
                lines=8
            )

            with gr.Row():
                age_input = gr.Number(
                    label="Patient Age",
                    value=35,
                    minimum=0,
                    maximum=120
                )
                weight_input = gr.Number(
                    label="Patient Weight (kg)",
                    value=70,
                    minimum=0,
                    maximum=300
                )

            verify_btn = gr.Button("🔍 Verify Prescription", variant="primary", size="lg")

            gr.Markdown("""
            ### ℹ️ Features:
            - 💊 NLP-Based Drug Extraction
            - ⚠️ Drug Interaction Detection
            - 📊 Age-Specific Dosage
            - 🔄 Alternative Suggestions
            """)

        with gr.Column(scale=2):
            gr.Markdown("## 📊 Analysis Results")

            with gr.Tab("💊 Detected Drugs"):
                drugs_output = gr.Markdown()

            with gr.Tab("⚠️ Drug Interactions"):
                interactions_output = gr.Markdown()

            with gr.Tab("📊 Dosage Recommendations"):
                dosage_output = gr.Markdown()

            with gr.Tab("🔄 Alternatives"):
                alternatives_output = gr.Markdown()

    # Examples
    gr.Examples(
        examples=[
            ["Patient prescribed Aspirin 325mg daily and Warfarin 5mg daily for cardiovascular protection.", 45, 75],
            ["Metformin 500mg twice daily and Lisinopril 10mg once daily for diabetes and hypertension management.", 58, 82],
            ["Amoxicillin 500mg three times daily for infection treatment.", 8, 30],
            ["Simvastatin 40mg at bedtime for cholesterol management. Patient also takes grapefruit juice daily.", 65, 78]
        ],
        inputs=[prescription_input, age_input, weight_input],
        label="📋 Example Prescriptions"
    )

    # Connect button to function
    verify_btn.click(
        fn=verify_prescription,
        inputs=[prescription_input, age_input, weight_input],
        outputs=[drugs_output, interactions_output, dosage_output, alternatives_output]
    )

# ============================================
# LAUNCH APP
# ============================================
print("\n" + "="*50)
print("🚀 Launching AI Medical Prescription Verification System...")
print("="*50 + "\n")

app.launch(share=True, debug=True)

